/**
 * Invoice
 */
export const INVOICE_ADD = "INVOICE_ADD";
export const INVOICE_VIEW = "INVOICE_VIEW";
export const INVOICE_EDIT = "INVOICE_EDIT";
export const INVOICE_SAVE_SUCCESS = "INVOICE_SAVE_SUCCESS";
export const INVOICE_SAVE_FAILURE = "INVOICE_SAVE_FAILURE";
export const INVOICE_DELETE = "INVOICE_DELETE";
export const INVOICE_CLOSEFORM = "INVOICE_CLOSEFORM";
export const INVOICE_ON_ROW_CLICK = "INVOICE_ON_ROW_CLICK";
export const INVOICE_REQUEST = "INVOICE_REQUEST";
export const INVOICE_OPEN_FILTER = "INVOICE_OPEN_FILTER";
export const INVOICE_CLOSE_FILTER = "INVOICE_CLOSE_FILTER";
export const INVOICE_FILTER_SUCCESS = "INVOICE_FILTER_SUCCESS";
export const INVOICE_FILTER_FAILURE = "INVOICE_FILTER_FAILURE";
export const INVOICE_LOADING    = "INVOICE_LOADING";