/**
 * Employee
 */
export const EMPLOYEE_ADD = "EMPLOYEE_ADD";
export const EMPLOYEE_VIEW = "EMPLOYEE_VIEW";
export const EMPLOYEE_EDIT = "EMPLOYEE_EDIT";
export const EMPLOYEE_DELETE = "EMPLOYEE_DELETE";
export const EMPLOYEE_CLOSEFORM = "EMPLOYEE_CLOSEFORM";
export const EMPLOYEE_REQUEST = "EMPLOYEE_REQUEST";
export const EMPLOYEE_SAVE_SUCCESS = "EMPLOYEE_SAVE_SUCCESS";
export const EMPLOYEE_SAVE_FAILURE = "EMPLOYEE_SAVE_FAILURE";
export const ON_ROW_CLICK = "ON_ROW_CLICK";
export const LOADING    = "LOADING";