/**
 * Company
 */
export const COMPANY_ADD = "COMPANY_ADD";
export const COMPANY_VIEW = "COMPANY_VIEW";
export const COMPANY_EDIT = "COMPANY_EDIT";
export const COMPANY_SAVE_SUCCESS = "COMPANY_SAVE_SUCCESS";
export const COMPANY_SAVE_FAILURE = "COMPANY_SAVE_FAILURE";
export const COMPANY_DELETE = "COMPANY_DELETE";
export const COMPANY_CLOSEFORM = "COMPANY_CLOSEFORM";
export const COMPANY_ON_ROW_CLICK = "COMPANY_ON_ROW_CLICK";
export const COMPANY_REQUEST = "COMPANY_REQUEST";
export const COMPANY_LOADING    = "COMPANY_LOADING";