/**
 * Taxes
 */

 export const INVOICE_TAXES_ON_ROW_CLICK = "INVOICE_TAXES_ON_ROW_CLICK";
 export const INVOICE_TAXES_CLOSEFORM    = "INVOICE_TAXES_CLOSEFORM";
 export const INVOICE_TAXES_LOADING      = "INVOICE_TAXES_LOADING";
