/**
 * Service
 */
export const SERVICE_ADD = "SERVICE_ADD";
export const SERVICE_VIEW = "SERVICE_VIEW";
export const SERVICE_EDIT = "SERVICE_EDIT";
export const SERVICE_SAVE_SUCCESS = "SERVICE_SAVE_SUCCESS";
export const SERVICE_SAVE_FAILURE = "SERVICE_SAVE_FAILURE";
export const SERVICE_DELETE = "SERVICE_DELETE";
export const SERVICE_CLOSEFORM = "SERVICE_CLOSEFORM";
export const SERVICE_ON_ROW_CLICK = "SERVICE_ON_ROW_CLICK";
export const SERVICE_REQUEST = "SERVICE_REQUEST";
export const SERVICE_LOADING    = "LOADING";

/**
 * Invoice Service
 */
export const INVOICE_SERVICE_ADD = "INVOICE_SERVICE_ADD";
export const INVOICE_SERVICE_VIEW = "INVOICE_SERVICE_VIEW";
export const INVOICE_SERVICE_EDIT = "INVOICE_SERVICE_EDIT";
export const INVOICE_SERVICE_SAVE_SUCCESS = "INVOICE_SERVICE_SAVE_SUCCESS";
export const INVOICE_SERVICE_SAVE_FAILURE = "INVOICE_SERVICE_SAVE_FAILURE";
export const INVOICE_SERVICE_DELETE = "INVOICE_SERVICE_DELETE";
export const INVOICE_SERVICE_CLOSEFORM = "INVOICE_SERVICE_CLOSEFORM";
export const INVOICE_SERVICE_ON_ROW_CLICK = "INVOICE_SERVICE_ON_ROW_CLICK";
export const INVOICE_SERVICE_REQUEST = "INVOICE_SERVICE_REQUEST";
export const INVOICE_SERVICE_LOADING    = "INVOICE_LOADING";