/**
 * Service
 */
export const SERVICE_ADD = "SERVICE_ADD";
export const SERVICE_VIEW = "SERVICE_VIEW";
export const SERVICE_EDIT = "SERVICE_EDIT";
export const SERVICE_SAVE_SUCCESS = "SERVICE_SAVE_SUCCESS";
export const SERVICE_SAVE_FAILURE = "SERVICE_SAVE_FAILURE";
export const SERVICE_DELETE = "SERVICE_DELETE";
export const SERVICE_CLOSEFORM = "SERVICE_CLOSEFORM";
export const SERVICE_ON_ROW_CLICK = "SERVICE_ON_ROW_CLICK";
export const SERVICE_REQUEST = "SERVICE_REQUEST";
export const LOADING    = "LOADING";