/**
 * Client
 */
export const CLIENT_ADD = "CLIENT_ADD";
export const CLIENT_VIEW = "CLIENT_VIEW";
export const CLIENT_EDIT = "CLIENT_EDIT";
export const CLIENT_SAVE_SUCCESS = "CLIENT_SAVE_SUCCESS";
export const CLIENT_SAVE_FAILURE = "CLIENT_SAVE_FAILURE";
export const CLIENT_DELETE = "CLIENT_DELETE";
export const CLIENT_CLOSEFORM = "CLIENT_CLOSEFORM";
export const CLIENT_ON_ROW_CLICK = "CLIENT_ON_ROW_CLICK";
export const CLIENT_REQUEST = "CLIENT_REQUEST";
export const CLIENT_OPEN_FILTER = "CLIENT_OPEN_FILTER";
export const CLIENT_CLOSE_FILTER = "CLIENT_CLOSE_FILTER";
export const CLIENT_FILTER_SUCCESS = "CLIENT_FILTER_SUCCESS";
export const CLIENT_FILTER_FAILURE = "CLIENT_FILTER_FAILURE";
export const CLIENT_LOADING    = "CLIENT_LOADING";