/**
 * Client
 */
export const CLIENT_ADD = "CLIENT_ADD";
export const CLIENT_VIEW = "CLIENT_VIEW";
export const CLIENT_EDIT = "CLIENT_EDIT";
export const CLIENT_SAVE_SUCCESS = "CLIENT_SAVE_SUCCESS";
export const CLIENT_SAVE_FAILURE = "CLIENT_SAVE_FAILURE";
export const CLIENT_DELETE = "CLIENT_DELETE";
export const CLIENT_CLOSEFORM = "CLIENT_CLOSEFORM";
export const CLIENT_ON_ROW_CLICK = "CLIENT_ON_ROW_CLICK";
export const CLIENT_REQUEST = "CLIENT_REQUEST";